name: Trubank CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      env:
        trusonaUsername: ${{ secrets.trusonaUsername }}
        trusonaPassword: ${{ secrets.trusonaPassword }}
      run: |
        echo "trusonaUsername: ${trusonaUsername}"
        echo "trusonaPassword: ${trusonaPassword}"
        ./gradlew build
    - name: Slack Notification
      uses: innocarpe/actions-slack@v1
      with:
        status: ${{ job.status }}
        success_text: 'Step Succeeded :trump-smile:'
        failure_text: 'Step Failed :trump-shaking:'
        cancelled_text: 'Step Cancelled :trump-hair:'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}