- name: Slack Notification
    uses: 8398a7/action-slack@v2
    with:
      status: ${{ job.status }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
    if: always()